apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    editable: true
    isDefault: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'tempo'